teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1

    axis_angular:  # Left thumb stick horizontal
      yaw: 3

    enable_button: 5  # Left trigger button